/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenSaleSol from "./TokenSale.sol";
export type { tokenSaleSol };
import type * as tokenShopSol from "./TokenShop.sol";
export type { tokenShopSol };
import type * as tokenizedBallotSol from "./TokenizedBallot.sol";
export type { tokenizedBallotSol };
export type { MyNFT } from "./MyNFT";
export type { MyToken } from "./MyToken";
