/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMyNFT,
  IMyNFTInterface,
} from "../../../contracts/TokenSale.sol/IMyNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMyNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IMyNFTInterface {
    return new Interface(_abi) as IMyNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMyNFT {
    return new Contract(address, _abi, runner) as unknown as IMyNFT;
  }
}
