/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TokenInterface,
  TokenInterfaceInterface,
} from "../../../contracts/TokenShop.sol/TokenInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class TokenInterface__factory {
  static readonly abi = _abi;
  static createInterface(): TokenInterfaceInterface {
    return new Interface(_abi) as TokenInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TokenInterface {
    return new Contract(address, _abi, runner) as unknown as TokenInterface;
  }
}
