/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tokenSaleSol from "./TokenSale.sol";
export * as tokenizedBallotSol from "./TokenizedBallot.sol";
export { MyNFT__factory } from "./MyNFT__factory";
export { MyToken__factory } from "./MyToken__factory";
